# Generated by Django 5.1.2 on 2024-10-15 07:12

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=banjo.models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='blocks',
            field=banjo.models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=banjo.models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rebounds',
            field=banjo.models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='steals',
            field=banjo.models.FloatField(default=0.0),
        ),
    ]
