# Generated by Django 5.1.2 on 2024-10-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_player_assists_alter_player_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='mvp',
        ),
    ]
